version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "18:00"
      timezone: "Europe/Paris"
    target-branch: development
