######################## default configuration ####################
baseURL = "https://royllo.org"
languageCode = "en-us"
title = "Royllo | Taro Asset Universe applications, services & tooling"
theme = "gosaas-hugo"

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"


############################## navigation ###############################
[menu]

  [[menu.main]]
  name = "What is Taro ?"
  URL = "taro"
  weight = 2

  [[menu.main]]
  name = "Our vision"
  URL = "vision"
  weight = 3

  [[menu.main]]
  name = "Our product"
  URL = "product"
  weight = 4

  ###################### footer menu
  [[menu.footer]]
  name = "What is Taro ?"
  URL = "whatIsTaro"
  weight = 2

  [[menu.footer]]
  name = "Our vision"
  URL = "ourVision"
  weight = 3

  [[menu.footer]]
  name = "Product"
  URL = "product"
  weight = 4


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "We provide applications, services & tooling for taro asset universes."
author = "Themefisher"
# Google Analitycs TODO fill google analtycs ID
googleAnalitycsID = "Your ID"
# copyright
copyright = "@2022 Royllo All Rights Reserved"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # Navigation get start button
  [params.navButton]
  enable = true
  label = "GitHub"
  link = "https://github.com/royllo"


############################### social links ############################
[[params.social]]
name = "Twitter"
link = "https://twitter.com/royllo_systems"

[[params.social]]
name = "Github"
link = "https://github.com/royllo"


########################### footer call to action #####################
[params.cta]
enable = false
title  = "Join 75,000+ growing businesses that <br> use Buffer to build their brands"
#button
label = "Get start with us"
link = "#"


############################ footer ##############################
[params.footer]
bgImage = "images/backgrounds/footer-bg.png"
content = "We provide applications, services & tooling for Taro Asset Universes."