######################## default configuration ####################
baseURL = "https://royllo.org"
languageCode = "en-us"
title = "Royllo | Taro Asset Universe applications, services & tooling"
theme = "gosaas-hugo"

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"


############################## navigation ###############################
[menu]

  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 2

  [[menu.main]]
  name = "Service"
  URL = "service"
  weight = 3

  [[menu.main]]
  name = "Team"
  URL = "team"
  weight = 4

  [[menu.main]]
  name = "Pricing"
  URL = "pricing"
  weight = 5

  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 6

  ###################### footer menu
  [[menu.footer]]
  name = "About"
  URL = "about"
  weight = 2

  [[menu.footer]]
  name = "Service"
  URL = "service"
  weight = 3

  [[menu.footer]]
  name = "Team"
  URL = "team"
  weight = 4

  [[menu.footer]]
  name = "Pricing"
  URL = "pricing"
  weight = 5

  [[menu.footer]]
  name = "Contact"
  URL = "contact"
  weight = 6


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "We provide applications, services & tooling for taro asset universes"
author = "Themefisher"
# Google Analitycs TODO fill google analtycs ID
googleAnalitycsID = "Your ID"
# copyright
copyright = "| @2022 Royllo All Rights Reserved |"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # Navigation get start button
  [params.navButton]
  enable = true
  label = "Visit our GitHub"
  link = "https://github.com/royllo"


############################### social links ############################
[[params.social]]
name = "Facebook"
link = "#"

[[params.social]]
name = "Twitter"
link = "#"

[[params.social]]
name = "Github"
link = "#"

[[params.social]]
name = "Linkedin"
link = "#"


########################### footer call to action #####################
[params.cta]
enable = true
title  = "Join 75,000+ growing businesses that <br> use Buffer to build their brands"
#button
label = "Get start with us"
link = "#"


############################ footer ##############################
[params.footer]
bgImage = "images/backgrounds/footer-bg.png"
content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has."

# card we accept
[[params.footer.card]]
image = "images/paypal.png"
[[params.footer.card]]
image = "images/visa.png"
[[params.footer.card]]
image = "images/a-express.png"